const { labs, tallSadd, lengths } = course;
const labKeys = Object.keys(labs);
const titles = {descriptive:'Deskriptiv statistik',regression:'Enkel linjär regression',inference:'Inferens',simulation:'Simulering'};
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = (n,d=1) => n.toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d});
const mean = a=>a.reduce((s,v)=>s+v,0)/a.length;
const key = 'r-labbar-progress-v1';
let memory = {done:{},last:null};
let storageOK = true;
try {
  const stored=JSON.parse(localStorage.getItem(key)||'null');
  if(stored&&typeof stored==='object') {
    for(const k of labKeys) memory.done[k]=Array.isArray(stored.done?.[k])?[...new Set(stored.done[k].filter(i=>Number.isInteger(i)&&i>=0&&i<labs[k].steps.length))]:[];
    if(stored.last&&labKeys.includes(stored.last.lab)&&Number.isInteger(stored.last.step)&&stored.last.step>=0&&stored.last.step<labs[stored.last.lab].steps.length) memory.last=stored.last;
  }
} catch { storageOK=false; }
const finished = k => memory.done[k]||[];
const percent = k => Math.round(finished(k).length/labs[k].steps.length*100);
function save(){try{localStorage.setItem(key,JSON.stringify(memory));}catch{storageOK=false;}storageStatus();}
function storageStatus(){document.querySelector('.save-indicator').innerHTML='<i></i> '+(storageOK?'Sparas i den här webbläsaren':'Sparas bara under detta besök');}
function route(){const p=location.hash.slice(1).split('/');if(p[0]==='labb'&&labKeys.includes(p[1]))return {page:'labb',lab:p[1],step:Math.min(labs[p[1]].steps.length-1,Math.max(0,(parseInt(p[2],10)||1)-1))};return{page:['oversikt','start','data','hjalp'].includes(p[0])?p[0]:'oversikt'};}
const href=(k,i=0)=>'#labb/'+k+'/'+(i+1);
const resume=k=>{const remaining=labs[k].steps.findIndex((_,i)=>!finished(k).includes(i));return memory.last?.lab===k?memory.last.step:remaining<0?0:remaining;};
const icon=(kind)=>'<svg width="26" height="26" viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">'+(kind==='descriptive'?'<path d="M5 23V14h4v9M12 23V5h4v18M19 23V10h4v13M3 23h22"/>':kind==='regression'?'<path d="M4 4v20h21M7 20L24 6"/><circle cx="9" cy="14" r="1.2"/><circle cx="14" cy="17" r="1.2"/><circle cx="18" cy="8" r="1.2"/><circle cx="23" cy="11" r="1.2"/>':kind==='simulation'?'<circle cx="14" cy="14" r="10"/><path d="M14 7v14M7 14h14M9 9l10 10M19 9L9 19" stroke-linecap="round"/>':'<path d="M2 22h24M3 21c6 0 5-16 11-16s5 16 11 16M14 5v17M8 19v3M20 19v3" stroke-linecap="round"/>')+'</svg>';
const progress=k=>'<div class="progress-track" role="progressbar" aria-label="Klara steg i '+esc(titles[k])+'" aria-valuemin="0" aria-valuemax="'+labs[k].steps.length+'" aria-valuenow="'+finished(k).length+'"><span style="width:'+percent(k)+'%"></span></div><div class="progress-caption"><span>'+finished(k).length+' av '+labs[k].steps.length+' steg klara</span><span>'+percent(k)+' %</span></div>';
function heading(eyebrow,title,copy){return '<div class="heading-row"><div><p class="eyebrow">'+eyebrow+'</p><h1>'+title+'</h1><p>'+copy+'</p></div></div>';}
function overview(){
 const total=labKeys.reduce((n,k)=>n+finished(k).length,0);
 const all=labKeys.reduce((n,k)=>n+labs[k].steps.length,0);
 const last=memory.last;
 return heading('Välkommen till R-Labbar','Statistik, ett steg i taget.','Fyra praktiska labbar som hjälper dig att gå från din första rad R-kod till egna statistiska slutsatser.')+
 '<section class="welcome"><div class="welcome-copy"><span class="pill">'+(last?'FORTSÄTT DÄR DU SLUTADE':'EN BRA BÖRJAN')+'</span><h2 style="margin-top:14px">'+(last?titles[last.lab]:'Ny i R? Du är på rätt plats.')+'</h2><p>'+(last?'Du var på steg '+(last.step+1)+': '+esc(labs[last.lab].steps[last.step].title)+'. Ta ett steg till i din egen takt.':'Lär känna RStudio, hämta ditt dataset och kör din första kod. Vi guidar dig hela vägen.')+'</p><a class="button primary" href="'+(last?href(last.lab,last.step):'#start')+'">'+(last?'Fortsätt labben':'Kom igång med R')+' <span aria-hidden="true">↗</span></a></div><div class="welcome-art" aria-hidden="true"><div class="mini-code"><div class="window-dots"><i></i><i></i><i></i></div><code># En liten början.<br>plantor &lt;- c(100, 111, 113)<br><br>mean(plantor)</code><div class="mini-result">[1] 108</div></div><div class="art-note">Din första insikt börjar här.</div></div></section>'+
 '<section aria-labelledby="labs-title"><div class="section-title"><h2 id="labs-title">Dina labbar</h2><span>'+total+' / '+all+' steg klara</span></div><div class="cards">'+labKeys.map(k=>'<article class="lab-card '+k+'"><div class="card-top"><div class="lab-icon">'+icon(k)+'</div><span class="card-index">LABB '+labs[k].number+'</span></div><h3>'+titles[k]+'</h3><p>'+labs[k].lede+'</p><div class="card-meta"><span>▤ '+labs[k].steps.length+' steg</span></div>'+progress(k)+'<a class="card-action" href="'+href(k,resume(k))+'">'+(percent(k)===100?'Repetera labben':finished(k).length?'Fortsätt labben':'Öppna labben')+'<span aria-hidden="true">→</span></a></article>').join('')+'</div></section>'+
 '<div class="bottom-grid"><section class="soft-card"><p class="eyebrow">SÅ FUNGERAR DET</p><h3>Förstå varje steg, i din egen takt.</h3><p>Läs instruktionen, kopiera koden till RStudio och jämför ditt resultat. Avsluta med att testa vad du har lärt dig.</p><div class="workflow"><b>01</b> Läs <span>→</span><b>02</b> Kör <span>→</span><b>03</b> Förstå</div></section><section class="soft-card"><p class="eyebrow">DINA ÖVNINGSDATA</p><h3>Riktiga data att utforska</h3><a class="file-mini" href="Tallsådd.xlsx" download><b class="file-badge">XLSX</b>Tallsådd<span>25 rader ↓</span></a><a class="file-mini" href="Längder.xlsx" download><b class="file-badge">XLSX</b>Längder<span>200 rader ↓</span></a></section></div>';
}
function highlight(code){return code.split('\n').map(line=>{let out='',pos=0;const re=/"[^"]*"|'[^']*'|#.*/g;let m;while((m=re.exec(line))){out+=esc(line.slice(pos,m.index));out+='<span class="'+(m[0].startsWith('#')?'code-comment':'code-string')+'">'+esc(m[0])+'</span>';pos=re.lastIndex;}return out+esc(line.slice(pos));}).join('\n');}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+esc(typeof v==='number'?fmt(v,Number.isInteger(v)?0:1):v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function chart(type){
 const x=v=>50+(v-70)/80*450;
 const bar=(label,value,max,y)=>'<text x="5" y="'+(y+14)+'" class="chart-label">'+label+'</text><rect x="44" y="'+y+'" width="'+(420*value/max)+'" height="21" rx="3" fill="#89a975"/><text x="'+(52+420*value/max)+'" y="'+(y+15)+'" class="chart-label">'+fmt(value,type==='means'?1:0)+'</text>';
 if(type==='means')return '<div class="diagram"><h3>Medelvärde per behandlingsgrupp</h3><svg viewBox="0 0 540 190" role="img" aria-label="Gruppmedelvärden: 97,8; 119,8; 128,6; 128,2; 127,2 plantor">'+[1,2,3,4,5].map((g,i)=>bar('B = '+g,mean(tallSadd.filter(r=>r[1]===g).map(r=>r[0])),150,10+i*35)).join('')+'</svg><p>Antal grodda plantor. Beräknat från alla 25 observationer.</p></div>';
 if(type==='hist'){
 const bounds=[70,90,110,130,150];const counts=bounds.slice(0,-1).map((b,i)=>tallSadd.filter(r=>(i===0?r[0]>=b:r[0]>b)&&r[0]<=bounds[i+1]).length);
 return '<div class="diagram"><h3>Hur är antalet grodda plantor fördelat?</h3><svg viewBox="0 0 540 240" role="img" aria-label="Histogram med frekvenser '+counts.join(', ')+'">'+[0,5,10,15,20].map(n=>'<line x1="45" y1="'+(190-n*7.5)+'" x2="505" y2="'+(190-n*7.5)+'" class="chart-grid"/><text x="35" y="'+(194-n*7.5)+'" text-anchor="end" class="chart-label">'+n+'</text>').join('')+counts.map((n,i)=>'<rect x="'+(45+i*115)+'" y="'+(190-n*7.5)+'" width="114" height="'+n*7.5+'" fill="#90ac7a" stroke="#fff"/><text x="'+(102+i*115)+'" y="'+(182-n*7.5)+'" text-anchor="middle" class="chart-label">'+n+'</text>').join('')+bounds.map((v,i)=>'<text x="'+(45+i*115)+'" y="210" text-anchor="middle" class="chart-label">'+v+'</text>').join('')+'<text x="275" y="233" text-anchor="middle" class="chart-label">Antal grodda plantor (Y)</text></svg><p>Y-axel: frekvens. Som i R hör ett gränsvärde till intervallet till vänster; det första intervallet inkluderar 70.</p></div>';
 }
 if(type==='box'){
 const rows=[1,2,3,4,5].map(g=>{const a=tallSadd.filter(r=>r[1]===g).map(r=>r[0]).sort((a,b)=>a-b);const q1=a[1],q3=a[3],iqr=q3-q1;const inside=a.filter(v=>v>=q1-1.5*iqr&&v<=q3+1.5*iqr);return{g,q1,med:a[2],q3,lo:inside[0],hi:inside.at(-1),out:a.filter(v=>!inside.includes(v))};});
 return '<div class="diagram"><h3>Median, spridning och avvikande observationer</h3><svg viewBox="0 0 540 225" role="img" aria-label="Boxplot för fem behandlingsgrupper. B1 ligger lägst. Avvikande värden: 112 och 144 i B4, 149 i B5.">'+[70,90,110,130,150].map(v=>'<line x1="'+x(v)+'" y1="10" x2="'+x(v)+'" y2="188" class="chart-grid"/><text x="'+x(v)+'" y="206" text-anchor="middle" class="chart-label">'+v+'</text>').join('')+rows.map((d,i)=>{const y=25+i*36;return '<text x="5" y="'+(y+4)+'" class="chart-label">B = '+d.g+'</text><line x1="'+x(d.lo)+'" y1="'+y+'" x2="'+x(d.hi)+'" y2="'+y+'" stroke="#739366"/><path d="M'+x(d.lo)+' '+(y-7)+'v14M'+x(d.hi)+' '+(y-7)+'v14" stroke="#739366"/><rect x="'+x(d.q1)+'" y="'+(y-10)+'" width="'+(x(d.q3)-x(d.q1))+'" height="20" rx="2" fill="#d9e7cb" stroke="#739366"/><line x1="'+x(d.med)+'" y1="'+(y-10)+'" x2="'+x(d.med)+'" y2="'+(y+10)+'" stroke="#254b3b" stroke-width="2"/>'+d.out.map(v=>'<circle cx="'+x(v)+'" cy="'+y+'" r="3" fill="none" stroke="#ba8458"/>').join('');}).join('')+'</svg><p>Strecket i boxen är medianen. Cirklar ligger utanför 1,5 × IQR från boxen, enligt R:s standardregel.</p></div>';
 }
 if(type==='scatter'){
 const xs=lengths.map(r=>r[0]),ys=lengths.map(r=>r[2]),mx=mean(xs),my=mean(ys);const b=xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0)/xs.reduce((s,x)=>s+(x-mx)**2,0);const a=my-b*mx;
 const px=v=>50+(v-150)*9,py=v=>220-(v-21)*16;
 return '<div class="diagram"><h3>Kroppslängd och fotlängd</h3><div class="chart-legend"><span><i></i>Kvinna</span><span class="second"><i></i>Man</span><span>— Gemensam regressionslinje</span></div><svg viewBox="0 0 540 270" role="img" aria-label="Alla 200 observationer och en gemensam regressionslinje. Positivt samband mellan kroppslängd och fotlängd.">'+[22,25,28,31].map(v=>'<line x1="50" y1="'+py(v)+'" x2="500" y2="'+py(v)+'" class="chart-grid"/><text x="40" y="'+(py(v)+4)+'" text-anchor="end" class="chart-label">'+v+'</text>').join('')+[150,160,170,180,190,200].map(v=>'<text x="'+px(v)+'" y="243" text-anchor="middle" class="chart-label">'+v+'</text>').join('')+'<text x="50" y="16" class="chart-label">Fotlängd (cm)</text><text x="275" y="266" text-anchor="middle" class="chart-label">Kroppslängd (cm)</text>'+lengths.map(d=>'<circle cx="'+px(d[0])+'" cy="'+py(d[2])+'" r="2.7" fill="'+(d[1]==='Man'?'#bb8b5d':'#739967')+'" opacity=".68"><title>'+esc(d[1])+': '+fmt(d[0])+' cm, fot '+fmt(d[2])+' cm</title></circle>').join('')+'<line x1="'+px(152.7)+'" y1="'+py(a+b*152.7)+'" x2="'+px(196.4)+'" y2="'+py(a+b*196.4)+'" stroke="#274e3d" stroke-width="2.3"/></svg><p>Samtliga 200 personer visas. Håll pekaren över en punkt för att se mätvärdena.</p></div>';
 }
 return '';
}
function lesson(k,i){
 const lab=labs[k],step=lab.steps[i],done=finished(k).includes(i),complete=percent(k)===100;
 const quiz=step.quiz?'<section class="quiz"><p class="eyebrow">KOLL PÅ LÄGET?</p><h3>'+esc(step.quiz.q)+'</h3><div class="quiz-options">'+step.quiz.options.map((o,j)=>'<button class="quiz-option" data-answer="'+j+'"><span class="option-letter">'+String.fromCharCode(65+j)+'</span>'+esc(o)+'</button>').join('')+'</div><p class="quiz-feedback" role="status" hidden></p></section>':'';
 const final=i===lab.steps.length-1;
 return '<div class="lesson-heading"><div class="lesson-meta"><span class="pill">LABB '+lab.number+'</span><span>'+lab.steps.length+' steg</span></div><h1>'+lab.title+'</h1><p>'+lab.lede+'</p></div>'+
 '<div class="lesson-layout"><div class="lesson-main"><div class="step-topline"><span>STEG '+(i+1)+' AV '+lab.steps.length+' · '+finished(k).length+' KLARA</span><div class="progress-track"><span style="width:'+percent(k)+'%"></span></div></div><article class="lesson-box"><div class="step-title"><span class="step-number">'+String(i+1).padStart(2,'0')+'</span><h2>'+esc(step.title)+'</h2></div><p class="purpose">'+step.purpose+'</p><p class="subtle-label">Kopiera och kör i RStudio. Resultatet här är en förklarad sammanfattning.</p><div class="code-grid"><section class="code-panel"><div class="panel-header"><span>R-KOD</span><button class="copy-button" data-copy>Kopiera kod ⧉</button></div><pre><code id="r-code">'+highlight(step.code)+'</code></pre></section><section class="output-panel"><div class="panel-header"><span>RESULTAT ATT JÄMFÖRA MED</span></div><pre>'+esc(step.output)+'</pre></section></div>'+
 (step.chart?chart(step.chart):step.table?table(step.table[0],step.table.slice(1)):'')+
 (step.interpretation?'<div class="interpretation">'+step.interpretation+'</div>':'')+
 (step.note?'<div class="note"><strong>Bra att veta</strong>'+step.note+'</div>':'')+
 '<section class="practice"><h3>✳ Prova själv</h3><p>'+esc(step.practice||'Kör koden och beskriv resultatet med egna ord.')+'</p></section>'+quiz+
 '<div class="step-actions"><button class="done-button" data-done aria-pressed="'+done+'">'+(done?'✓ Steget är klart':'○ Markera som klart')+'</button>'+(final?'<a class="button primary" href="#oversikt">Till översikten →</a>':'<a class="button primary" href="'+href(k,i+1)+'">Nästa steg →</a>')+'</div></article>'+
 (complete?'<section class="complete-banner" role="status"><h3>Du har gått igenom hela labben!</h3><p>Alla '+lab.steps.length+' steg är markerade som klara. Du kan alltid komma tillbaka och repetera.</p>'+(labKeys.indexOf(k)<2?'<a class="button primary" href="'+href(labKeys[labKeys.indexOf(k)+1])+'">Öppna nästa labb →</a>':'<a class="button" href="#oversikt">Se dina framsteg →</a>')+'</section>':'')+
 '<div class="lesson-bottom">'+(i>0?'<a class="button ghost" href="'+href(k,i-1)+'">← Föregående steg</a>':'<a class="button ghost" href="#start">← Startguiden</a>')+'<a class="button ghost" href="#hjalp">Jag har fastnat ↗</a></div></div>'+
 '<aside class="lesson-side"><section class="step-list"><h2>I den här labben</h2><nav aria-label="Labbens steg">'+lab.steps.map((s,j)=>'<a class="step-link '+(j===i?'active ':'')+(finished(k).includes(j)?'done':'')+'" href="'+href(k,j)+'" '+(i===j?'aria-current="step"':'')+'><span class="step-n">'+(finished(k).includes(j)?'✓':j+1)+'</span><span>'+esc(s.title)+'</span></a>').join('')+'</nav>'+progress(k)+'</section><section class="soft-card"><p class="eyebrow">TILL DEN HÄR LABBEN</p><h3>'+lab.file+'</h3><p>'+(k==='descriptive'?'25':k==='simulation'?'0':'200')+' rader · '+(k==='simulation'?'simuleringskod':'3 variabler')+'</p><a class="button" href="'+lab.fileUrl+'" download>Dataset ↓</a><a class="button" href="'+k+'.R" download>Hela labbens R-kod ↓</a></section><section class="soft-card"><p class="eyebrow">ATT HA MED SIG</p><h3>'+lab.short+'</h3><p>'+lab.quick.join('</p><p>')+'</p></section></aside></div>';
}
function start(){
 return heading('DIN FÖRSTA STUND I R','Kom igång, i lugn och ro.','Du behöver R, RStudio och ett dataset. Följ de fyra stegen och öppna sedan din första labb.')+
 '<div class="guide-grid"><section class="guide-card"><p class="eyebrow">01 · INSTALLERA</p><h2>R räknar. RStudio hjälper dig.</h2><p>Installera först R, som gör beräkningarna. Installera sedan RStudio Desktop, där du skriver kod och ser resultat. Båda finns i kostnadsfria versioner.</p><div class="guide-links"><a class="button" href="https://cran.r-project.org/" target="_blank" rel="noopener">Hämta R ↗</a><a class="button" href="https://posit.co/download/rstudio-desktop/" target="_blank" rel="noopener">Hämta RStudio ↗</a></div></section>'+
 '<section class="guide-card"><p class="eyebrow">02 · SKAPA EN ARBETSPLATS</p><h2>Samla ditt arbete i ett projekt.</h2><ol><li>Öppna RStudio och välj <strong>File → New Project → New Directory → New Project</strong>.</li><li>Döp projektet till <strong>R-Labbar</strong> och välj en mapp.</li><li>Öppna <strong>File → New File → R Script</strong> och spara som <strong>labb1.R</strong>.</li></ol><p>Skriv din kod i skriptet så att du kan spara och återanvända den.</p></section>'+
 '<section class="guide-card"><p class="eyebrow">03 · HÄMTA DATA</p><h2>Två filer. Fyra labbar.</h2><p>Deskriptiv statistik använder Tallsådd.xlsx. Regression och inferens använder Längder.xlsx. Spara filerna i projektmappen.</p><div class="guide-links"><a class="button" href="Tallsådd.xlsx" download>Tallsådd.xlsx ↓</a><a class="button" href="Längder.xlsx" download>Längder.xlsx ↓</a></div><p style="margin-top:17px">I varje labb öppnar <code>file.choose()</code> en filväljare, så att du kan välja filen även om den ligger i Hämtade filer.</p></section>'+
 '<section class="guide-card"><p class="eyebrow">04 · KÖR DIN FÖRSTA RAD</p><h2>Skriv. Kör. Läs resultatet.</h2><p>Skriv detta i ditt R-skript:</p><span class="inline-code">mean(c(100, 111, 113))</span><p>Placera markören på raden och tryck <strong>Ctrl + Enter</strong> (Windows) eller <strong>Cmd + Enter</strong> (Mac). I <strong>Console</strong> visas <code>[1] 108</code>. Du har räknat ut ett medelvärde!</p><p><strong>Environment</strong> visar sparade objekt. <strong>Plots</strong> visar diagram.</p></section>'+
 '<section class="guide-card wide-card"><p class="eyebrow">LITE R-SPRÅK SOM HJÄLPER</p><h2>Fem tecken du snart känner igen.</h2><p><code>&lt;-</code> sparar ett värde i ett objekt. <code>$</code> väljer en kolumn. <code>#</code> börjar en kommentar. <code>c()</code> samlar värden i en vektor. <code>~</code> läses ”förklaras av” i en modellformel.</p><p>R skiljer på stora och små bokstäver. Skriv decimaler med punkt i koden, till exempel <code>0.95</code>.</p><a class="button primary" href="'+href('descriptive')+'">Öppna labb 01: Deskriptiv statistik →</a></section></div>';
}
function datasets(){
 return heading('FILER ATT ARBETA MED','Dataset & R-filer','Hämta originalfilerna, kika på innehållet och ladda ner ett R-skript för varje labb.')+
 [['Tallsådd',['Y','B','A'],tallSadd,'25 observationer av grodda tallplantor. Y är antal grodda plantor, B behandlingsgrupp och A försöksrad.'],['Längder',['Längd_cm','Kön','Fotlängd_cm'],lengths,'200 personer med kroppslängd, gruppen Kön och fotlängd. Båda längdmåtten anges i centimeter.']].map(([name,headers,rows,description])=>'<section class="dataset-section"><p class="eyebrow">DATASET · '+rows.length+' RADER · 3 VARIABLER</p><h2>'+name+'</h2><p>'+description+'</p><div class="dataset-toolbar"><div class="dataset-buttons"><a class="button primary" href="'+name+'.xlsx" download>Hämta Excel-fil ↓</a><a class="button" href="'+name+'.csv" download>Hämta CSV ↓</a></div><button class="button" data-expand="'+name+'" aria-expanded="false">Visa alla '+rows.length+' rader</button></div><div id="table-'+name+'">'+table(headers,rows.slice(0,6))+'</div><p class="subtle-label" style="margin-top:10px">Excel-filen är originalet. CSV-filen innehåller samma värden och använder komma som kolumnavgränsare.</p></section>').join('')+
 '<section class="dataset-section"><h2>Labbarnas R-skript</h2><p>Öppna filen i RStudio och kör ett avsnitt i taget. Hämta också datasetet som hör till labben.</p><div class="guide-links">'+labKeys.map(k=>'<a class="button" href="'+k+'.R" download>Labb '+labs[k].number+' · R-fil ↓</a>').join('')+'</div></section>';
}
function help(){
 const terms=[['Objekt','Ett namn som sparar data eller ett resultat. resultat <- lm(...) sparar en modell som resultat.'],['Funktion','Ett kommando som gör något med indata. mean(x) räknar ut medelvärdet av x.'],['Data frame / tibble','En tabell där kolumnerna är variabler och raderna observationer.'],['Standardavvikelse','Ett mått på spridning kring medelvärdet, i samma enhet som variabeln.'],['Residual','Observerat värde minus modellens anpassade värde. Hjälper dig att bedöma modellen.'],['Konfidensintervall','Ett intervall för en okänd populationsparameter. En 95-procentig metod täcker det sanna värdet i cirka 95 % av upprepade stickprov under antagandena.'],['P-värde','Sannolikheten, om nollhypotesen och testets antaganden stämmer, att få ett minst lika extremt testresultat som det observerade.'],['Statistisk signifikans','Ett resultat kallas signifikant när p-värdet är mindre än vald signifikansnivå. Det säger inte hur stor eller praktiskt viktig effekten är.']];
 return heading('DET ÄR OKEJ ATT FASTNA','Begrepp & hjälp','Små förklaringar till stora frågor. Börja med felmeddelandet och kontrollera sedan raden som gav felet.')+
 '<dl class="glossary">'+terms.map(([t,d])=>'<div class="term"><dt>'+t+'</dt><dd>'+d+'</dd></div>').join('')+'</dl><h2>Vanliga frågor i RStudio</h2>'+
 [['”There is no package called readxl”','Kör <code>install.packages("readxl")</code> en gång med internetanslutning. Kör sedan <code>library(readxl)</code>. Efter omstart av R behöver du ladda paketet igen.'],['”Could not find function read_excel”','Kör <code>library(readxl)</code> innan du läser filen. Ett installerat paket är inte automatiskt laddat i varje session.'],['”Object not found”','Kör först raden som skapar objektet. Kontrollera stavning, stora och små bokstäver samt svenska tecken. <code>Längder</code> och <code>längder</code> är olika namn.'],['R hittar inte min Excel-fil','Kör importen med <code>read_excel(file.choose())</code> och välj rätt fil i dialogrutan. <code>getwd()</code> visar arbetsmappen om du använder ett filnamn direkt.'],['Jag får NA i stället för ett resultat','NA betyder att ett värde saknas. Undersök först med <code>sum(is.na(x))</code>. I exempelvis <code>mean(x, na.rm = TRUE)</code> ignoreras saknade värden, men tänk igenom varför de saknas innan du fortsätter.'],['Console visar + i stället för >','R väntar på att du ska avsluta exempelvis en parentes eller ett citattecken. Tryck Esc för att avbryta och kontrollera sedan koden.'],['Varför ser min output annorlunda ut?','Här visas förklarade, avrundade sammanfattningar av R:s output. Antalet decimaler, utskriftsformatet och vissa testinställningar kan skilja mellan versioner. Jämför främst skattningar, intervall och slutsatser.'],['Kan jag köra R-koden på den här sidan?','Koden körs i RStudio på din dator. Webbplatsen ger instruktioner, datadiagram och kunskapsfrågor. Kopieringsknappen kopierar koden utan att köra den.'],['Var sparas mina framsteg?','Steg du markerar som klara sparas lokalt i den här webbläsaren. De synkroniseras inte mellan enheter och kan försvinna om du rensar webbplatsdata. Inget konto behövs.']].map(([q,a])=>'<details class="faq"><summary>'+q+'</summary><p>'+a+'</p></details>').join('')+
 '<section class="soft-card" style="margin-top:24px"><h3>Läs mer i dokumentationen</h3><div class="guide-links"><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html" target="_blank" rel="noopener">t.test ↗</a><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html" target="_blank" rel="noopener">lm ↗</a><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/binom.test.html" target="_blank" rel="noopener">binom.test ↗</a><a href="https://readxl.tidyverse.org/" target="_blank" rel="noopener">readxl ↗</a></div></section>'+
 '<div class="reset-box"><h3>Börja om med dina framsteg</h3><p>Rensa dina markeringar och din sparade position i den här webbläsaren.</p><button class="button" data-reset>Nollställ framsteg</button><div id="reset-confirm" hidden><p>Vill du ta bort alla dina markeringar? Detta går inte att ångra.</p><button class="button" data-reset-confirm>Ja, nollställ</button> <button class="button" data-reset-cancel>Behåll framstegen</button></div></div>';
}
function render(scroll=true){
 const r=route();const main=document.getElementById('main');
 const labels={oversikt:'Översikt',start:'Kom igång',data:'Dataset & R-filer',hjalp:'Begrepp & hjälp',labb:titles[r.lab]};
 document.getElementById('breadcrumb').textContent=labels[r.page];
 document.title='R-Labbar · '+labels[r.page];
 document.getElementById('lab-nav').innerHTML=labKeys.map(k=>'<a class="lab-nav-item '+(r.lab===k?'active':'')+'" href="'+href(k,resume(k))+'" '+(r.lab===k?'aria-current="page"':'')+'><span class="number">'+labs[k].number+'</span><span><strong>'+titles[k]+'</strong><small>'+finished(k).length+' av '+labs[k].steps.length+' steg klara</small></span></a>').join('');
 document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===r.page);if(a.dataset.nav===r.page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(r.page==='labb'){memory.last={lab:r.lab,step:r.step};save();main.innerHTML=lesson(r.lab,r.step);}else main.innerHTML=({oversikt:overview,start,data:datasets,hjalp:help}[r.page])();
 if(scroll){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}
 storageStatus();
}
let toastTimer;
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{t.hidden=true;},3500);}
document.addEventListener('click',async event=>{
 const t=event.target.closest('button');if(!t)return;
 const r=route();
 if(t.hasAttribute('data-copy')&&r.page==='labb'){
  try{if(!navigator.clipboard?.writeText)throw Error('unavailable');await navigator.clipboard.writeText(labs[r.lab].steps[r.step].code);t.textContent='Kopierad ✓';toast('Koden är kopierad. Klistra in den i RStudio.');setTimeout(()=>{if(t.isConnected)t.textContent='Kopiera kod ⧉';},2000);}
  catch{const range=document.createRange();range.selectNodeContents(document.getElementById('r-code'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('Kopiering blockerades. Tryck Ctrl+C eller Cmd+C för att kopiera den markerade koden.');}
 }
 if(t.hasAttribute('data-done')&&r.page==='labb'){const a=finished(r.lab);memory.done[r.lab]=a.includes(r.step)?a.filter(n=>n!==r.step):[...a,r.step];save();render(false);document.querySelector('[data-done]').focus({preventScroll:true});}
 if(t.hasAttribute('data-answer')&&r.page==='labb'){
  const quiz=labs[r.lab].steps[r.step].quiz;const correct=Number(t.dataset.answer)===quiz.answer;
  document.querySelectorAll('[data-answer]').forEach(b=>{b.classList.remove('correct','incorrect');b.setAttribute('aria-pressed',String(b===t));});
  t.classList.add(correct?'correct':'incorrect');const f=document.querySelector('.quiz-feedback');f.hidden=false;f.textContent=correct?quiz.explain:'Inte riktigt. Läs tolkningen ovan och prova igen.';
 }
 if(t.hasAttribute('data-expand')){
  const name=t.dataset.expand,expanded=t.getAttribute('aria-expanded')==='true',rows=name==='Tallsådd'?tallSadd:lengths,headers=name==='Tallsådd'?['Y','B','A']:['Längd_cm','Kön','Fotlängd_cm'];
  document.getElementById('table-'+name).innerHTML=table(headers,expanded?rows.slice(0,6):rows);
  t.setAttribute('aria-expanded',String(!expanded));t.textContent=expanded?'Visa alla '+rows.length+' rader':'Visa bara 6 rader';
 }
 if(t.hasAttribute('data-reset')){document.getElementById('reset-confirm').hidden=false;t.hidden=true;}
 if(t.hasAttribute('data-reset-cancel')){document.getElementById('reset-confirm').hidden=true;document.querySelector('[data-reset]').hidden=false;}
 if(t.hasAttribute('data-reset-confirm')){memory={done:{},last:null};save();render(false);toast('Dina framsteg är nollställda.');}
});
window.addEventListener('hashchange',()=>render());
render(false);
